### PR TITLE
Enable notifications to be shown on Android Lock Screen

### PR DESCRIPTION
**Pull request by richturner**
Just allows notifications to be shown on the Lock Screen. This should maybe be a configurable option or maybe enabled by default with configurable option to make it private

### CODE REVIEW

**Comment by richturner** [comment]
This should maybe be a configurable option or maybe enabled by default with configurable option to make it private

**Comment by huang475** [comment]
+1

**Comment by Artfloriani** [comment]
Nice! The openApp flag is great! Is there any way of opening the app when using the on click call back?

**Comment by jondspa** [comment]
Hi -

  Does this branch still work?  I'm trying to show a notification on the lock screen on Android.  If the phone is awake, I get both a sound and a text alert at the top of the page.  If the phone is locked, I only get the sound.  I'm using these parameters in NotificationCompat.Builder in Builder.java

                .setDefaults(0)
                .setPriority(2)
                .setVisibility(NotificationCompat.VISIBILITY_PUBLIC)

Thanks!   - Jon

**Comment by katzer** [comment]
Thats possible now - thanks

**Pull request closed without merging**
