### PR TITLE
(android) support new features for notification icons

### PR DESCRIPTION
**Pull request by dpa99c**
(android) feat: Support night mode for notification icons
(android) feat: Support using vector icons for notifications

### CODE REVIEW

**Comment by GitToTheHub** [comment]
Can you please explain, what your code does? Have the user something to setup?
Why do you have this code in this PR:
```javascript
        if(LocalNotification.isInForeground() && !options.triggerInForeground())
            return;
```
It seems, this belongs to another PR.

**Comment by dpa99c** [comment]
yes, I somehow screwed up the branches and this code is from the android_foreground PR - will update now to fix

**Comment by GitToTheHub** [comment]
You added the documentation for the foreground option on the wrong pr. Can you also only add changes to the readme regarding the foreground property? It seems, your IDE formatted the whole table in the readme.

**Comment by dpa99c** [comment]
sorry, I'm ill with the flu so I'll leave this until tomorrow morning when
my brain is fresh and have another go

**Comment by GitToTheHub** [comment]
No problem, take a good cure :)

**Comment by dpa99c** [comment]
I've updated this branch to document the usage of icons on Android in README.md and also made the other changes you requested. It's rebased onto the current master so should be OK to merge.

An example project demonstrating the working usage of this feature is here:
https://github.com/dpa99c/cordova-plugin-local-notifications-test

**Comment by GitToTheHub** [comment]
Hi, thanks for you changes. You made a great documentation! I did a review, please check the points.

**Review by GitToTheHub — COMMENTED** [review]
I forgot to submit my review :D

**Comment by GitToTheHub** [comment]
Hi @dpa99c, would you mind if you would make the changes to this PR so I can merge it? Thanks.

**Comment by dpa99c** [comment]
I don't have time to spend on this at the moment. You are welcome to make the requested changes, otherwise I will look at it when I have some time.

**Comment by GitToTheHub** [comment]
Thanks I will see if I can do it

**Comment by GitToTheHub** [comment]
Hi,

I partially added you PR:

- I used some of your documentation for documenting the [res://](https://github.com/katzer/cordova-plugin-local-notifications#resource-pattern-res) path of this plugin. There is described, how you copy a resource to the `res` directory and how to use it. I also documented, that it can also be a vector drawable.
- I took over the code for creating a Bitmap form a vector drawable

Regarding dark mode:
The plugin uses the corresponding drawable for the current device settings. So you can put your dark mode drawable in `drawable-night` and the right drawable will be used, if the device is in dark mode.

Thank you!

Regards

**Pull request closed without merging**
