### PR TITLE
Fix for cordova-android-4.0

### PR DESCRIPTION
**Pull request by krishlakshmanan**
Fix for cordova-android-4.0

### CODE REVIEW

**Comment by miraculixx** [comment]
are there any plans to merge this PR? thanks.

**Comment by Anu2g** [comment]
Hey @krishlakshmanan , I'm thinking about using this in my project. Are there no side effects to removing android-support-v4.jar? Eg. do we need to add a gradle file and add it into there? Thanks in advance!

**Comment by wilianto** [comment]
Thank you.. Now it works well for me..

**Comment by krishlakshmanan** [comment]
Hi @Anu2g ,
There is no side effects by removing android-support-v4.jar .

**Pull request closed without merging**
