### PR TITLE
Update LocalNotification.java for compatibility with the new default android platform - android@4.0.0 

### LINKED ISSUE #518: Problem with the new default android platform - android@4.0.0
Hi,

I have just updated my cordova project to android@4.0.0.
Now cordova uses Grandle to build by defaults (https://cordova.apache.org/announcements/2015/04/15/cordova-android-4.0.0.html).

I received errors during building:
```
..../platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:495: error: cannot find symbol
                    webView.evaluateJavascript(js, null);
                           ^
  symbol:   method evaluateJavascript(String,<null>)
  location: variable webView of type CordovaWebView
..../platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:492: error: cannot find symbol
        webView.post(new Runnable(){
               ^
  symbol:   method post(<anonymous Runnable>)
  location: variable webView of type CordovaWebView
Note: Recompile with -Xlint:deprecation for details.
2 errors
:compileArmv7DebugJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileArmv7DebugJava'.
> Compilation failed; see the compiler error output for details.
```
Any help please?
Thanks

### PR DESCRIPTION
**Pull request by sapk**
Should fix #518

### CODE REVIEW

**Comment by dexity** [comment]
This fix only gets rid of compilation errors but I don't think it works. CordovaWebView no longer extends WebView. In 4.0.0 it is an interface.

**Comment by sapk** [comment]
You are right about the extends so it doesn't implement .post(Runnable) now but the cordovawebview still describe .loadUrl et .sendJavascript (wich is deprecated now)

 https://github.com/apache/cordova-android/blob/master/framework/src/org/apache/cordova/CordovaWebView.java

**Comment by jullian-chavez** [comment]
This seems to have fixed the issue for me.

**Comment by rosterloh** [comment]
Works for me too

**Comment by jough** [comment]
+1

**Pull request closed without merging**
