### PR TITLE
Notification Actions/Buttons

### PR DESCRIPTION
**Pull request by DavidBriglio**
This implements actions/buttons in the notification on android. This is done using the 'action' parameter:

``` javascript
cordova.plugins.notification.local.schedule({
    id: 1,
    title: "Action Notification",
    text: "Click on an action",
    actions: [
        { 
            text: "MAP",
            icon: "res://ic_menu_mapmode", //A drawable icon (Optional)
            action: 0   //Any additional values apart from text and icon will be transferred along
                        //to be used in your handler function. Here I used "action", but you can
                        //add multiple fields with any key/value. See below for more examples.
        },
        {
            text: "Select",
            action: 1,
            myAction: "action1"
        },
        {
            text: "Ignore",
            action: 2,
            anotherValue: 0
        }
        //Note: There can only be up to three actions (enforced by android)
    ]
});
```

How Actions Are Handled:

When you add your action to the notification, the only required field is "text". This will display the action button without any icon. When the action is clicked it will fire a "click" event, passing into it the entry in the actions array. This entry will have an inserted "notification" element containing the rest of the notification. This allows any key/value inserted into your action element in the actions array to be passed into the handler function.

ie:

``` javascript
cordova.plugins.notification.local.schedule({
    id: 1,
    title: "Test",
    actions: [
        {
            text: "Action1", 
            val: 1
        },
        {
            text: "Action2",
            val: 100
        }
    ]
});
```

When "Action1" is clicked, the "click" event will fire, sending this as the notification parameter:

``` javascript
{
    text: "Action1",
    val: 1,
    notification: {
        id: 1,
        title: "Test",
        actions: [
            {
                text: "Action1", 
                val: 1
            },
            {
                text: "Action2",
                val: 100
            }
        ]
    }
}
```

Great icons to use for the actions: [Google Material Icons](https://design.google.com/icons/)

### CODE REVIEW

**Comment by rwillett** [comment]
I assume this is not working in iOS then

**Comment by DavidBriglio** [comment]
@rwillett This is for Android only.

**Comment by makinhs** [comment]
Any chance to make this feature working also in ios?

**Comment by DavidBriglio** [comment]
@makinhs I do not have plans to add this functionality to iOS anytime soon.

**Comment by s4msagaz** [comment]
when will be this option available? (at least for android) i tried to use "actions" but looks like are not supported for my version...

**Comment by Artfloriani** [comment]
@s4msagaz You could also try my experimental fork: https://github.com/Artfloriani/LocalNotification

It is up to date with katzer updates, working on Android and iOS **but** it was done just for what I needed and might be inconsistent between the platforms (different callback objects, view comments on the example on READ-ME). I've been running a production app for a while now and so far I got no issues with it. I plan to improve the compatibility and fix the commit history to use the original author of each commit (lost the author when merging with katzer iOS10 branch), but I currently do not have time for it. 

Hope it helps for now ;)

**Comment by DavidBriglio** [comment]
@s4msagaz @makinhs I have created a new notification plugin for iOS only here: https://github.com/DavidBriglio/cordova-ios10-simple-notification

**Comment by katzer** [comment]
Actions have been added - thanks

**Pull request closed without merging**
