### PR TITLE
Set alertTitle to same as alertBody for Apple Watch

### PR DESCRIPTION
**Pull request by tommi**
See issue #415

### CODE REVIEW

**Comment by leecrossley** [comment]
+1 I'd like to see this merged in, thanks @tommi

**Comment by leecrossley** [comment]
On second though, probably don't want the alertTitle to be the alertBody, as they have very different purposes (short/long-look notifications). Should be implemented in the JS interface as title, since iOS doesn't currently use that property.

**Comment by leecrossley** [comment]
I decided it best for me to add this method directly to my [apple watch plugin](https://github.com/leecrossley/cordova-plugin-apple-watch).

**Comment by mix3d** [comment]
I agree with @leecrossley on not having them be the same: Android's function is to use the title in the config separately from the text, why not mirror that? However, since the default function of title for non-watch notifications is to not use it, leaving it as `title` becomes misleading if you set the title text but never see it because you don't have a watch.

**Pull request closed without merging**
