### PR TITLE
Fix bug where repeating weekly notifications would fire every second

### PR DESCRIPTION
**Pull request by jmeyers91**
This fixes the issue I was running into in #1810

### CODE REVIEW

**Comment by danemco** [comment]
This patch didn't work for me. I still get notifications every second for a whole minute.

**Comment by danemco** [comment]
Nevermind! I figured it out. I had to remove my android platform and re-add it, and remove the plugin and re-add it with this patch to get it to work.

**Comment by katzer** [comment]
@jmeyers91 or @danemco Could you provide a code snippet. I tried to reproduce that as follows:

```js
trigger: { every: { hour: 11, minute: 26 } }
// or
trigger: { every: { hour: 11, minute: 26, weekday: 4 } }
```

It always triggers once.

**Comment by danemco** [comment]
@katzer, yes, I can reproduce it. This is how I reproduce the issue:

1. `cordova plugin install cordova-plugin-local-notifications` to install the plugin into my project
2. `cordova run build` to create a debug .apk
3. I copy that debug .apk to my Android emulator (running Android 9). I then launch my app.
4. I open up Chrome -> Developer Tools -> More Tools -> Remove Devices, and pick my app running in the simulator. This gives me a javascript console so that I can test the app.
5. I create a notification like the following, setting the notification to happen a minute or so in advance

```
cordova.plugins.notification.local.schedule({
   title: "Text Notification",
   text: "Testing a notification.",
   trigger: {
      every: {
      hour: 11,
      minute: 28,
      }
   }
});
```

Then wait until 11:28 and then the notification appears but keeps going over and over and over and over until the minute passes. I clear the notification and it immediate reappears. The app becomes unresponsive as well (probably because it's so busy processing the notification). 

@jmeyers91's patch worked for me, It sets the "seconds" to zero so the notification matches for that one moment, rather than the duration of the entire minute it's 11:28.

I hope that helps, and I would really like to see this fix merged in.

**Comment by katzer** [comment]
> `cordova plugin install cordova-plugin-local-notifications` to install the plugin into my project

Do you use __beta.2__ or __beta.3__? I fixed a similar issue (eb41d94f626402718d4c5eaa35ebca1045856709) in the latest beta.

**Comment by orhan-swe** [comment]
@katzer 
I am getting same issue using master (beta.2). I will try with beta.3 and see if it helps..

**Comment by orhan-swe** [comment]
@katzer 
It is working correctly in beta.3. It would be good if this is merged to master as this bug is totally breaking repeating trigger every time the date matches. 

I am seeing another issue (both beta.2 and beta.3). I am injecting a callback but the callback is not firing on trigger instead it is firing on schedule function execution. Is this a known issue?

**Comment by orhan-swe** [comment]
@katzer 
I would first like to thank you for putting time on this plugin. 
About the other issue I had, I was misunderstanding what the callback injected with scheduler function does. Now I see it executes when scheduler has been register successfully and does not execute on trigger. To get a callback to execute on trigger I need to use .on("trigger"...) Now when I know how it works it makes since but it did take me some time to understand this. Documentation is good but it was not 100% clear on this.

**Pull request merged**
