### PR TITLE
Improved docs

### PR DESCRIPTION
**Pull request by 0x1ad2**
Improved README file, did some grammar checks and made example more clear.

### CODE REVIEW

**Comment by 0x1ad2** [comment]
@rwillett no problem, happy to help, could you merge the PR?

**Comment by 0x1ad2** [comment]
No sure if it needs to be `open` to get merged, opening it again.

**Comment by rwillett** [comment]
Rats, thought I had. 

I have now.

**Comment by rwillett** [comment]
Brain failure on my part.

**Pull request merged**
