### PR TITLE
Headup  not displayed for local notification of oreo and above version.

### PR DESCRIPTION
**Pull request by AshwiniKhandagale**
I am facing the issue of headUp was not display for Android 8 or above version, Then I have review the plugin I saw one mistake. Priority is set to IMPORTANCE_DEFAULT. I have to make a small change priority set to IMPORTANCE_HIGH.

### CODE REVIEW

**Comment by CodeWithOz** [comment]
@katzer thanks a lot for all your hard work. Is there any chance of this getting merged? Or if there's a problem with the PR can you please give some feedback on what needs to be changed? Thanks!

**Comment by CodeWithOz** [comment]
@AshwiniKhandagale thanks for the PR, it's very useful. I've seen that you use a default channel called "VirGo". I have a number of channels that my app uses so that single one won't work for me. What do you suggest? I've forked your branch and I'm considering just making the channel names dynamic (based on values I supply), but do you have any suggestions? Or have you solved that problem in a different way? Thanks!

**Comment by rahmadid** [comment]
@CodeWithOz Hi, perhaps you can try this fork, it is more recent and still maintained (to my knowledge):
https://github.com/timkellypa/cordova-plugin-local-notifications

This fork also includes updates for Android 10.

Hope it helps. Thanks.

**Comment by CodeWithOz** [comment]
@rahmadid thanks yeah it's doing what I want it to do, thanks for pointing me in that direction!

**Comment by GitToTheHub** [comment]
Channels will be configurable in the future.

**Pull request closed without merging**
