### PR TITLE
0.8 Android O support

### PR DESCRIPTION
**Pull request by rahulk11**
Added support for android oreo by implementing NotificationChannels.

### CODE REVIEW

**Comment by shi11** [comment]
hi @rahulk11 nice work, I'm curious if you've tried this fix for the 0.9.0-beta1 build?

**Comment by rahulk11** [comment]
Hi @shi11 thanks for appreciation. 
No, I haven't tried yet. But, i'll be tryin it this weekend.

**Comment by katzer** [comment]
Thanks, I will merge it without testing...

**Comment by shi11** [comment]
hi @rahulk11 just checking in on whether you've had success with updating your branch's fix to 0.9.0-beta2? 

I'm getting this error when I try to build Android
`/Users/shillinger/Javascript/dropsMobile/platforms/android/src/de/appplant/cordova/plugin/notification/Builder.java:32: 
error: package android.support.v4.media.app.NotificationCompat does not exist
import android.support.v4.media.app.NotificationCompat.MediaStyle;`

thanks in advance :)

**Comment by katzer** [comment]
@shi11 The compilation error indicates that you have to upgrade your Android SDK. You need the latest one even your runtime versions are lower.

**Comment by rahulk11** [comment]
Hey @shi11 I've been busy lately, but I'm working on it. I hope to get it done soon.

**Comment by rahulk11** [comment]
Hi @shi11, I was looking at the base repository code and what i've found that code for android oreo support is already there. So, if you have any specific problem let me know.

**Comment by rahulk11** [comment]
@katzer Thanks for merging my changes to 0.8 
Can you please release this updated version also, because some people were complaining about not getting the latest code when adding plugin to cordova.
Thanks again.

**Comment by shi11** [comment]
hi @katzer thanks for the advice here. I'm still getting this error `package android.support.v4.media.app.NotificationCompat does not exist` and I'm not sure why.

I'm using Ionic 1.0
Android sdk: 26
Cordova-android 6.3.0

Any direction would be much appreciated. Thanks in advance, Seth

**Comment by rahulk11** [comment]
@shi11 Can you check if your gradle file contains this maven repository ?

maven {
            url "https://maven.google.com"
        }

**Comment by shi11** [comment]
Figured it out, thanks @rahulk11. @katzer was right!

The issue turned out to be related to this plugin: https://github.com/dpa99c/cordova-android-support-gradle-release - once I bumped up the version there, it fixed the issue.

**Comment by rahulk11** [comment]
@shi11 Glad to know that you got it fixed 👍

**Comment by colonelchlorine** [comment]
@katzer Is there a reason this PR / ticket was merged into 0.8 and it's not in master?

**Pull request merged**
