### PR TITLE
Change background color of small icon on Android.

### PR DESCRIPTION
**Pull request by Eusebius1920**
Added a simple modification that allows to change the background color of the circle behind the small icon on android. (I think it is Lollipop or later.)

Samle usage:
Sample image

```javascript
plugin.notification.local.schedule({id:1}); // The lower notification in the picture
plugin.notification.local.schedule({id:2, text:'Hello, test', color:'0FF0FF'}); // The upper notification in the picture
```

I hope this is not a duplicate to another pull request, but I didn't find one.

### CODE REVIEW

**Comment by katzer** [comment]
@Eusebius1920  may you could update your PR because there are merge conflicts. Tks!

**Comment by Eusebius1920** [comment]
Yes, I will do that, but you will have to wait until december. Before that I won't have much time to adapt it!

**Comment by Eusebius1920** [comment]
It should work again!

**Comment by katzer** [comment]
@Eusebius1920 The PR contains commits made by myself and some lines are different now. I will manually insert your additions.

**Comment by katzer** [comment]
@Eusebius1920 5cb48c4 Thank you!

**Pull request closed without merging**
