### PR TITLE
(android) fix: apply the logic for options.foreground

### PR DESCRIPTION
**Pull request by dpa99c**
apply the logic for options.foreground to decide whether to show notification

### CODE REVIEW

**Comment by GitToTheHub** [comment]
Hi, did you miss something with this PR? You added the method `triggerInForeground` but it is not used anywhere.

**Comment by dpa99c** [comment]
oops yes you're correct, I missed some files in the commit - will update

**Comment by GitToTheHub** [comment]
Thanks. Can you comment what this code does and why it is there?
```java
if(LocalNotification.isInForeground() && !options.triggerInForeground())
    return;
```

Can you document the foreground property in the readme?

**Comment by dpa99c** [comment]
[`LocalNotification.isInForeground()`](https://github.com/dpa99c/cordova-plugin-local-notifications/blob/android_foreground/src/android/LocalNotification.java#L690) is an existing function which returns true if the app is currently in the foreground.
[`options.triggerInForeground()`](https://github.com/dpa99c/cordova-plugin-local-notifications/blob/android_foreground/src/android/notification/Options.java#L184) returns true if the `foreground` option is set to `true`.
So the conditions combined means that the notification will not be shown if the app is in the foreground and `foreground` option is not set to true.
The reasoning for this is that you may not want to show a system notification if the app is being used and is in the foreground - instead you may wish to show an in-app dialog as part of the app UI.
I will update the README to make this clear.

**Comment by dpa99c** [comment]
Documentation is added to the README.md so this should be good to merge

**Comment by GitToTheHub** [comment]
Hi @dpa99c, would you mind if you would make the changes to this PR so I can merge it? Thanks.

**Comment by GitToTheHub** [comment]
Hi @dpa99c,

I checked to support `foreground` in Android. The correct behavior would be, to trigger the notification with the sound, vibration and badging, but not show it visually. In iOS, the notification is not shown, when `foreground` is `false` and it appears not in the Notification Center, but the device will make a sound, when it's not muted, vibrate and changes the badge, if a badge is set. In Android it's not possible to post a notification without showing it. The only solution would be, to play manually the sound of the notification channel, vibrate if set in the channel, and setting the badge manually. This feels not right, to simulate a triggered notification. Since iOS 14, there is a new presentation option called `UNNotificationPresentationOptionBanner`. This allows to present the notification in the Notification Center, but not as a banner, when the app is in foreground, when the `foreground` option is `false`. This presentation option is now always applied, to be consistent to Android. The `foreground` option was renamed to `iOSForeground` to imply, that it is a iOS only option. The question is, if on Android a notification can be shown as a banner like on iOS. If so, the `foreground` option could handle this behavior also on Android.

Regards,

Manuel

**Pull request closed without merging**
