### PR TITLE
Actions (on 0.9-dev)

### PR DESCRIPTION
**Pull request by elizabethrego**
Supersedes #774.

### CODE REVIEW

**Comment by katzer** [comment]
@elizabethrego If you will fix the merge conflicts I will merge it

**Comment by elizabethrego** [comment]
Ok, I will work on this and the property name changes this morning.

**Comment by katzer** [comment]
@elizabethrego :+1:
Could you also squash the commits please. One or two commits might be good enough.

**Comment by elizabethrego** [comment]
Merge conflicts resolved, property names changed, and documentation updated in first comment on #744. Please let me know if there's anything else I can do to get this merged! :)

**Comment by elizabethrego** [comment]
Ok, all done.

**Comment by katzer** [comment]
@elizabethrego Seems like you rebased agains master and not 0.9-dev ;)

**Comment by katzer** [comment]
@elizabethrego Thanks again for your effort! Until the final release of 0.9 there might be chances regarding actions. But I hope npm supports beta tags to make them available at early stage.

**Comment by elizabethrego** [comment]
Argh, sorry about that! I am not so good with git beyond the basic stuff. Thanks for the merge, and if there's anything I can do in the future please let me know!

**Comment by katzer** [comment]
@elizabethrego Sure if you like to help. To release v0.9 as next I need to add [actions for windows 10 platform](http://blogs.msdn.com/b/tiles_and_toasts/archive/2015/07/08/toast-notification-and-action-center-overview-for-windows-10.aspx) and [wearables](#321).

Let me know!
Sebastián

**Comment by elizabethrego** [comment]
Ok, I will see what I can do! I don't have any Windows 10 devices but maybe I can just work with an emulator...I do have an Android watch, but as I remember, the v4 support library included is missing a lot of classes - some of which are definitely needed for the wearable actions.

**Comment by kjt1212** [comment]
Hi guys,

I am trying to experiment with this branch. I cloned the project and checked out the 0.9-dev branch. After that I copied code from this branch to the corresponding plugin folders in ios and android platform of my ionic project. However, am unable to build the ios project after that. For android it does build correctly, however, the notifications do not contain the buttons. Am I adding this WIP plugin the correct way in my project or am I missing out on some steps? Looking forward to your reply.

**Comment by elizabethrego** [comment]
The actions code on iOS includes things available only in iOS 9 - if you don't have the iOS 9 SDK downloaded it won't build. I will work on pointing out the offending code as it's only necessary for replying directly from a notification action.

**Comment by kjt1212** [comment]
Hey @elizabethrego thanks for responding. I verifed that I have ios 9 sdk. This is the error that it shows:
duplicate symbol _UIApplicationRegisterUserNotificationSettings in:
    /Volumes/Data/letsTryAgainOnceMore/platforms/ios/build/letsTryAgainOnceMore.build/Debug-iphonesimulator/letsTryAgainOnceMore.build/Objects-normal/i386/AppDelegate+APPAppEvent.o
    /Volumes/Data/letsTryAgainOnceMore/platforms/ios/build/letsTryAgainOnceMore.build/Debug-iphonesimulator/letsTryAgainOnceMore.build/Objects-normal/i386/AppDelegate+APPRegisterUserNotificationSettings.o
ld: 1 duplicate symbol for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

It is declared in both those files and I tried commenting out one of them. Then it did build successfully, however, as soon as the code of schedule is called the app crashes. Sorry am absolutely new to cordova and have 0 experience with ios so am not sure if commenting that line was the right fix or not. Probably commenting it is causing some flow issue and the app is crashing. However, if I keep the code as is I get the above mentioned error. Have I missed something?

**Comment by elizabethrego** [comment]
I'm sorry, I really don't know anything about those errors. It may be something else in that branch that's causing the issue. Try using this repo:https://github.com/elizabethrego/cordova-plugin-local-notifications (interface slightly different) and see if you get the same error?

**Comment by kjt1212** [comment]
This is the 
Yes I tried that repo too. With that it builds and executes for both ios and android, however, the notification on ios does not have buttons.

You mentioned the interface is slightly different. So what is the interface if I use this repo?
This is how I am scheduling it currently using this repo:
var actions = [ {
          identifier: 'MEDICINE_TAKEN',
          title: 'Yes',
          activationMode: 'background'
        },
          {
            identifier: 'MORE_SIGNIN_OPTIONS',
            title: 'Snooze',
            activationMode: 'foreground'
          },
          {
            identifier: 'PROVIDE_INPUT',
            title: 'Skip',
            activationMode: 'background'
          }];
          cordova.plugins.notification.local.schedule({
            id: 300,
            title: "Lets see if this works",
            text: "Refill Due",
            ongoing: true,
            actions: [actions[0], actions[1], actions[2]],
            category: 'SIGN_IN_TO_CLASS'
          }, callback);

**Comment by elizabethrego** [comment]
Looks good to me. Try debugging the processNotificationInteractions method in UIApplication+APPLocalNotification.m to see if there's anything going wrong.

**Comment by kjt1212** [comment]
It forms the categories correctly I suppose. I debugged the function and it went smoothly this was the final object that was formed:
{(
    <UIMutableUserNotificationCategory: 0x7f98f1511bc0; identifier: (null), actions: {
    0 =     (
        "<UIMutableUserNotificationAction: 0x7f98f1708d70; identifier: MEDICINE_TAKEN, title: Yes, behavior: UIUserNotificationActionBehaviorDefault, activationMode: UIUserNotificationActivationModeBackground, isAuthenticationRequired:NO, isDestructive:NO, parameters: (null)>",
        "<UIMutableUserNotificationAction: 0x7f98f14ce2f0; identifier: MORE_SIGNIN_OPTIONS, title: Snooze, behavior: UIUserNotificationActionBehaviorDefault, activationMode: UIUserNotificationActivationModeForeground, isAuthenticationRequired:NO, isDestructive:NO, parameters: (null)>",
        "<UIMutableUserNotificationAction: 0x7f98f3910100; identifier: PROVIDE_INPUT, title: Skip, behavior: UIUserNotificationActionBehaviorDefault, activationMode: UIUserNotificationActivationModeBackground, isAuthenticationRequired:NO, isDestructive:NO, parameters: (null)>"
    );
    1 =     (
        "<UIMutableUserNotificationAction: 0x7f98f14ce2f0; identifier: MORE_SIGNIN_OPTIONS, title: Snooze, behavior: UIUserNotificationActionBehaviorDefault, activationMode: UIUserNotificationActivationModeForeground, isAuthenticationRequired:NO, isDestructive:NO, parameters: (null)>",
        "<UIMutableUserNotificationAction: 0x7f98f1708d70; identifier: MEDICINE_TAKEN, title: Yes, behavior: UIUserNotificationActionBehaviorDefault, activationMode: UIUserNotificationActivationModeBackground, isAuthenticationRequired:NO, isDestructive:NO, parameters: (null)>"
    );
}>
)}

**Comment by elizabethrego** [comment]
Ok, that's definitely not anything like how we want it to look. I will look into this tonight and get back to you.

**Comment by kjt1212** [comment]
oh ohk .. am a novice with respect to ios and swift so difficult for me to identify. Thank you so much @elizabethrego I really appreciate this! :)

**Comment by kjt1212** [comment]
@elizabethrego Hi there, I understand that you are busy, however, just wanted to ask if you got a chance to look at the issue with ios interactive notifications mentioned above?

**Comment by peepsilog** [comment]
@elizabethrego I tried using your plugin and when the **_activationMode_** is **foreground** for iOS, the buttons does not cascade to the apple watch but if it is **background** it goes to the apple watch.  Is there a rule why it is not allowing the buttons to cascade to the apple watch?

**Comment by mpateck** [comment]
Hello everyone, 

just wanted to know, if there is any chance to get the actions into the master in the near future?

Thanks

**Pull request merged**
