### PR TITLE
Only alert once option

### PR DESCRIPTION
**Pull request by jdevuono54**
I added onlyAlertOnce option and updated readme file

### CODE REVIEW

**Comment by GitToTheHub** [comment]
Thanks and now you can squash everything to one commit :)

**Comment by jdevuono54** [comment]
Everything should be good now. Thanks for the quick responses! :)

**Comment by GitToTheHub** [comment]
Thanks, but the whitespaces of the properties table are in again.

**Comment by GitToTheHub** [comment]
> Everything should be good now. Thanks for the quick responses! :)

No problem, did you saw my last comment?

**Comment by jdevuono54** [comment]
Ahh, sorry, it's my IDE that makes the modification during the commit. I'll fix it as soon as possible.

**Comment by GitToTheHub** [comment]
Ok thanks, if your IDE does this automatically, you can make a pr for adding the whitespaces. My IDE does not do this automatically. Which IDE do you use?

**Comment by jdevuono54** [comment]
PhpStorm

**Comment by GitToTheHub** [comment]
ok thanks

**Comment by jdevuono54** [comment]
That should be good ! :)

**Comment by GitToTheHub** [comment]
Hi thank you, your IDE changed something on the last line in the readme in L576, please revert this

**Comment by jdevuono54** [comment]
Sorry ><, do you have any idea when a new release with the new option will be available?

**Comment by GitToTheHub** [comment]
You can use the master-branch to use the new option. Thanks for your PR.

**Pull request merged**
