### PR TITLE
Fix If icon or sound are changed, uri isn't updated

### PR DESCRIPTION
**Pull request by dansanti**
This happens with update options , only icon or sound reference are finally updated and the effective sound, still fired with old uri.

### CODE REVIEW

**Comment by katzer** [comment]
@dansanti, may you could update your PR because there are merge conflicts. Tks!

**Comment by dansanti** [comment]
ok! I just upgrated my fork,  try now please.

**Comment by katzer** [comment]
@dansanti Is that only this single [commit](ec054d5df5e9647ce6d0daee4d2011be991b51fe)?

**Comment by dansanti** [comment]
yes, it'is a small fix

**Pull request closed without merging**
