### PR TITLE
Fixes iOS 7 crash

### PR DESCRIPTION
**Pull request by craig-at-rsg**
Crash detailed here:
https://github.com/katzer/cordova-plugin-local-notifications/issues/387

### CODE REVIEW

**Comment by TimoStolz** [comment]
+1

**Comment by joshbuckley182** [comment]
I've given this fix a go, but no notifications are appearing under iOS7.1. 

I did notice that `__IPHONE_OS_VERSION_MAX_ALLOWED` is used elsewhere in the code; maybe related to that?

**Comment by TimoStolz** [comment]
The fix targets the crash #387, not the visibilty of notifications.

To reproduce the crash, please
- build the app with SDK 8.1
- and run this app on a device with iOS7

*What happens now?* Since `__IPHONE_OS_VERSION_MAX_ALLOWED` is evaluated at compile time, the condition holds true and the code is included during compilation. That's why this code will be executed even on devices older than iOS8.

*What is the fix doing?* The fix above solves this problem using runtime checks for the iOS version rather than compile time checks for the SDK.

**Comment by katzer** [comment]
@craig-at-rsg, thanks for your PR and description. However I saw it to late but have merged it manually.

**Pull request closed without merging**
