### PR TITLE
Optional led blinking and switch to remove notification on application kill

### PR DESCRIPTION
**Pull request by mircoc**
Optional led blinking:
added a property for notification to disable led blinking (withLed: false)

Optional vibration:
added a property for notification to disable vibration (withVibration: false)

Switch to remove notification on application kill:
if setAutoClearAll() is called on plugin and the application is killed from android task manager than all notification will be removed

### CODE REVIEW

**Comment by JcDenton86** [comment]
Hi! Have these options been merged to the master branch? can I use them?

**Comment by katzer** [comment]
@mircoc may you could update your PR because there are merge conflicts. Tks!

**Comment by mircoc** [comment]
Hi @katzer, i updated my PR. Let me know!

**Comment by katzer** [comment]
@mircoc Optional led and vibration have been added.

**Pull request closed without merging**
