### PR TITLE
fix crash on samsung devices, 500 alarms limit, fix IOS 10 notifications

### PR DESCRIPTION
**Pull request by uareurapid**
On many samsung devices the app crashes while trying to add/schedule the notifications, due to the issue reported here:
http://developer.samsung.com/forum/board/thread/view.do?boardName=General&messageId=280286&listLines=15&startId=zzzzz%7E&searchSubId=0000000001
It seems that the fix done in the plugin does not entirely solves entirely the issue, as per some user reports
One way to avoid the nasty crash could be simply adding a try / catch on the `schedule` method

### CODE REVIEW

**Comment by uareurapid** [comment]
these changes adresses 2 different issues

**Comment by TheJKM** [comment]
Register a notification works like a charm, thanks! Can you also implement deleting notifications on iOS 10?

**Comment by uareurapid** [comment]
@TheJKM Check the `clear` and `clearAll` methods

**Comment by TheJKM** [comment]
I checked both `clear` and `cancel` methods (the ...All don't work for my app), `cancel` works for cancelling not yet triggered notifications, but `clear` does not remove triggered notifications from notification center.

**Comment by uareurapid** [comment]
are you talking about repetitive notifications? if it was triggered already why are you taking about clearing it? i didn´t get you point unless you´re referring to something that repeats over time...sorry but  don´t understand your scenario

**Comment by philecom** [comment]
Are you saying the plugin clears a notification after it is triggered, as long as it is NOT a repetitive notification?

**Comment by TheJKM** [comment]
That's what I meant. The 'original' plugin was able to delete fired notifications from notification center with `clear`. This iOS 10 version is not able to delete those.

**Comment by katzer** [comment]
The code catches such exceptions now - thanks

**Pull request closed without merging**
