### PR TITLE
Add support of BigPictureStyle for Android

### PR DESCRIPTION
**Pull request by HabibMAALEM**
## Attach large image to the notification

``` javascript
cordova.plugins.notification.local.schedule({
    id: 1,
    title: "Production Jour fixe",
    text: "Duration 1h",
    firstAt: monday_9_am,
    every: "week",
    sound: "file://sounds/reminder.mp3",
    icon: "http://icons.com/?cal_id=1",
    banner: "http://lorempixel.com/640/480/cats/",
    data: { meetingId:"123#fg8" }
});
```

### CODE REVIEW

**Comment by cdorner** [comment]
@HabibMAALEM  Are you thinking in add some other styles of notifications? (e.g inbox)

**Comment by mix3d** [comment]
@cdorner Thinking about this more: considering all the different types of Android's notification styles, and possibly even the addition of notification action buttons, would create a level of single-platform customization that might warrant forking this plugin to create an Android-only version. (unless the other platforms ignore the android specific customizations gracefully?)

Just a thought; I'd love to see all that functionality available to my apps as well.

**Comment by natanraj** [comment]
@cdorner : can you please help how i can show a background image on a notification? in some thread you mentioned about attaching a banner on 'trigger' event . **How to do it?**  And can the banner point to non-assets like /image folder or src like http ? Please kindly help. 

This is a big decision for my client to use this plugin on something else to look for.

**Comment by shivanipatel-8710** [comment]
Hello @HabibMAALEM ,..I tried your solution but image is not displaying in notification..my code is here please help me to solve it

          cordova.plugins.notification.local.schedule({
                id: $scope.data.notificationid,
                title: $scope.data.title,
                text: $scope.data.message,
                icon: 'res://icon',
                smallIcon: 'res://icon',
                banner: 'http://ims.studyfield.com/Resources/SingleNotification/10128/hm_1180938778.jpg'
                
            }).then(function (result) {
                console.log('Notification 1 triggered');
            });

**Comment by katzer** [comment]
Support for has been added - thanks

**Pull request closed without merging**
