### PR TITLE
Android 10 updates

### PR DESCRIPTION
**Pull request by timkellypa**
Android 10 support.
- Android 10 device support.
- Android 10 SDK support (androidx libraries).

Note:  This request is dependant on my other PR's (which are included).  These include changes for Android 8+ Notification Channel support, autoLaunch support, and support to adjust volume controls in Android when a notification is fired.

### CODE REVIEW

**Comment by expresscalendar** [comment]
Hi, I've been playing around with code in this and other beta branches but cannot get it to work on my OnePlus with Oxygen9. 
The issue is with triggering notifications in the future  - the notifications is correctly scheduled (and AlarmManager triggered at correct time ass shown in logcat) but the reciever does not get called (the onRecieve breakpoint is not hit in Android Studio).
I was wondering what OSes have you tested this with?
Thanks.

**Comment by timkellypa** [comment]
@expresscalendar I've really only tested my changes with Samsung S9, S10, and a few older Samsung devices.  There may be something specific to that OS that is not making it fire.  I'm also testing with a very specific use case.  My updates are just so my particular application will work, and I've not really done regression testing on features that I do not use.

However, my application does rely on exact notification times, so I may be able to help, assuming your problem is not OS-specific.

A few things to try if you rely on exact, real-time notifications, and if you happen to be testing this while the device is idle:

1. Be sure you set the priority to the max, 2.  That makes it use setAlarmClock instead of setExactAndAllowWhileIdle, the latter of which does not actually guarantee that it will fire on time.
2. Set wakeup to true.  That will make it acquire a wakelock.
3. You may need to remove the app from battery optimization.  I've added a couple methods to the plugin to manage this (requestIgnoreBatteryOptimizations being the main one) and have documented how they work, but beware that I've heard of that causing issues with the app store unless you have a good reason.

If you have an example of the object that you're sending to the notification plugin's schedule method, I can give it a try on one of my devices to see if I can reproduce your issue.  Then at least we'll know if it's specific to that device/OS.

**Comment by timkellypa** [comment]
> Hi, I've been playing around with code in this and other beta branches but cannot get it to work on my OnePlus with Oxygen9.
> The issue is with triggering notifications in the future - the notifications is correctly scheduled (and AlarmManager triggered at correct time ass shown in logcat) but the reciever does not get called (the onRecieve breakpoint is not hit in Android Studio).
> I was wondering what OSes have you tested this with?
> Thanks.

@expresscalendar I've really only tested my changes with Samsung S9, S10, and a few older Samsung devices. There may be something specific to that OS that is not making it fire. I'm also testing with a very specific use case. My updates are just so my particular application will work, and I've not really done regression testing on features that I do not use.

However, my application does rely on exact notification times, so I may be able to help, assuming your problem is not OS-specific.

A few things to try if you rely on exact, real-time notifications, and if you happen to be testing this while the device is idle:
1. Be sure you set the priority to the max, 2. That makes it use setAlarmClock instead of setExactAndAllowWhileIdle, the latter of which does not actually guarantee that it will fire on time.
2. Set wakeup to true. That will make it acquire a wakelock.
3. You may need to remove the app from battery optimization. I've added a couple methods to the plugin to manage this (requestIgnoreBatteryOptimizations being the main one) and have documented how they work, but beware that I've heard of that causing issues with the app store unless you have a good reason.

If you have an example of the object that you're sending to the notification plugin's schedule method, I can give it a try on one of my devices to see if I can reproduce your issue. Then at least we'll know if it's specific to that device/OS.

**Comment by expresscalendar** [comment]
@timkellypa Thanks for getting back to me so promptly.
The issue is the app is wide awake and the problem persists. I went back and added extra priority flag alas to no avail. Here is the full notification object as returned from getScheduled() call:

{"id":1589449628661,
"title":"Event title",
"text":"Starts ‎Today at 09:18‎.",
"trigger":{"at":1589447880000,"type":"calendar"},
"priority":2,
"wakeup":true,
"data":"{\"instanceId\":\"5ebd0c9a98ae411750dbfd3d\",\"scheduleId\":\"5e94a25356625650f4c2f3af\",\"updatedOn\":1589447834694}",
"smallIcon":"res://ic_launcher.png",
"color":"#56D8FF",
"launch":true,
"actions":[],
"alarmVolume":-1,
"attachments:[],
"autoLaunch":false,
"autoClear":true,
"clock":true,
"defaults":0,
"groupSummary":false,
"led":true,
"lockscreen":true,
"number":0,
"progressBar":{"enabled":false,"value":0,"maxValue":100,"indeterminate":false},
"resetDelay":5,
"silent":false,
"sound":true,
"timeoutAfter":null,
"vibrate":false,
"fullScreenIntent":false,
"triggerInApp":false,
"meta":{"plugin":"cordova-plugin-local-notification","version":"0.9-beta.3"}}

Strangely the meta field shows version 0.9-beta.3? I do have the correct package installed in node-modules (shows beta-4).

Bizzarely I have managed to get it working for one notification (triggered in the future) at a time using https://github.com/katzer/cordova-plugin-local-notifications/issues/1862#issuecomment-591992151 - another notification added before the first one was triggered resulted in 'cancelation' of the first one.

Anyway, I'll try to reset my device and start afresh as `adb shell dumpsys alarm` reveals thousands of pending alarms for my app.

**Comment by expresscalendar** [comment]
@timkellypa Right, after device restart with no scheduled alarms the problem persists. I get a 
`05-14 11:02:00.008  2547  3313 V AlarmManager: Triggering alarm #1: 0 when =1589450520000 package =com.expresscalendar.app operation =*walarm*:NOTIFICATION_ID314132658-2 flags =0x3` entry in the log showing the alarm was correctly run but the notification does not get shown.

I'll go back to https://github.com/katzer/cordova-plugin-local-notifications/issues/1862#issuecomment-591992151 to see what the diff in code is that made the notification work before.

**Comment by timkellypa** [comment]
I think in my app, I always have an "after" on the trigger.  I'm not looking at the code now, but when you go to schedule, maybe set 

`trigger: {
   after: new Date().getTime()
}`

I think that parameter was relatively new to new versions of the plugin and is used as a fail safe to make sure alarms don't fire for things that were scheduled in the past.  It couldn't really be defaulted in the builder because the notifications are rebuilt prior to firing.

As far as the version being wrong, that was my fault.  I didn't update it in all the proper locations.  I don't know if/when it will be merged and what the version will be then, but just in case, I'll try to fix that up when I get a chance.

**Comment by timkellypa** [comment]
> 
> 
> @timkellypa Right, after device restart with no scheduled alarms the problem persists. I get a
> `05-14 11:02:00.008 2547 3313 V AlarmManager: Triggering alarm #1: 0 when =1589450520000 package =com.expresscalendar.app operation =*walarm*:NOTIFICATION_ID314132658-2 flags =0x3` entry in the log showing the alarm was correctly run but the notification does not get shown.
> 
> I'll go back to [#1862 (comment)](https://github.com/katzer/cordova-plugin-local-notifications/issues/1862#issuecomment-591992151) to see what the diff in code is that made the notification work before.

I think in my app, I always have an "after" on the trigger. I'm not looking at the code now, but when you go to schedule, maybe set

`trigger: { after: new Date().getTime() }`

I think that parameter was relatively new to new versions of the plugin and is used as a fail safe to make sure alarms don't fire for things that were scheduled in the past. It couldn't really be defaulted in the builder because the notifications are rebuilt prior to firing.

As far as the version being wrong, that was my fault. I didn't update it in all the proper locations. I don't know if/when it will be merged and what the version will be then, but just in case, I'll try to fix that up when I get a chance.

**Comment by expresscalendar** [comment]
Thanks @timkellypa, so I have discovered the culprit in why https://github.com/katzer/cordova-plugin-local-notifications/issues/1862#issuecomment-591992151 only schedule a single notification - I used timestamp for my notification id which is > java.Integer.MAX and it got truncated which resulted in all my notifs having the same bloody id. Argh. Anyway, got it working with THAT branch, now I'm going to test with yours.

**Comment by timkellypa** [comment]
@expresscalendar sounds good, thanks!  Let me know if there are some additional changes I need to pull in to get it working for you.  I'd be happy to do so.

**Comment by expresscalendar** [comment]
@timkellypa, apologies for getting back to you soo late but had my hands tied with crazy deadlines. I can now confirm your branch works for OnePlus, after the manifest target fix.
Thanks a lot for good work!

**Comment by timkellypa** [comment]
@expresscalendar glad things are working for you!  Thanks for helping to track the issue down.  Please let me know if you run into any other issues.

**Comment by amit-lulla** [comment]
@timkellypa : When I try to use your code, I get an error on Android build. Please guide what is it that I'm missing in my code?

 (truncated) ...  error: package NotificationCompat does not exist
                 NotificationCompat.Builder builder;
error: cannot find symbol
                 Message[] messages = options.getMessages();
                 ^
           symbol:   class Message
           location: class Builder
error: package NotificationCompat does not exist
                 NotificationCompat.MessagingStyle style;
error: package NotificationCompat does not exist
                 style = new NotificationCompat.MessagingStyle("Me")

de/appplant/cordova/plugin/notification/Builder.java:253:

**Comment by timkellypa** [comment]
> @timkellypa : When I try to use your code, I get an error on Android build. Please guide what is it that I'm missing in my code?
> 
> (truncated) ... error: package NotificationCompat does not exist
> NotificationCompat.Builder builder;
> error: cannot find symbol
> Message[] messages = options.getMessages();
> ^
> symbol: class Message
> location: class Builder
> error: package NotificationCompat does not exist
> NotificationCompat.MessagingStyle style;
> error: package NotificationCompat does not exist
> style = new NotificationCompat.MessagingStyle("Me")
> 
> de/appplant/cordova/plugin/notification/Builder.java:253:

@amit-lulla It seems that the references to the androidx libraries are broken for you.  If you are not targeting Android 10 in your project, please see if the following note in my changelog helps you.

    "Note: If you are not building with API 29 on Android, you can use https://www.npmjs.com/package/cordova-plugin-androidx for backwards compatibility."

If not let me know and I'll see if there's something else going on.

**Comment by shankari** [comment]
In case anybody else is looking to see when this will be merged, I switched to using the version from https://github.com/timkellypa/cordova-plugin-local-notifications.git instead and it works fine for me.

```
cordova plugin rm cordova-plugin-local-notifications
cordova plugin add https://github.com/timkellypa/cordova-plugin-local-notifications.git
```

**Comment by RafaelKr** [comment]
Thanks @shankari! But there's a little mistake in the remove command, it should be "notification" instead of "notifications"

```
cordova plugin rm cordova-plugin-local-notification
cordova plugin add https://github.com/timkellypa/cordova-plugin-local-notifications.git
```

**Comment by mstoecke** [comment]
@timkellypa Any chances to change background and text color of notifications?

**Comment by alixti** [comment]
If anyone has troubles building @timkellypa you can use the [this plugin](https://github.com/dpa99c/cordova-plugin-androidx-adapter) created by @dpa99c 

Next, you need to enable the AndroidX support by adding the next code into your project's config.xml file:

`<preference name="AndroidXEnabled" value="true" />`

**Comment by jbagaresgaray** [comment]
Any news on this PR? When is this going to be merge or approved?

**Comment by timkellypa** [comment]
> @timkellypa Any chances to change background and text color of notifications?

It doesn't look like it currently supports this.  I haven't done extensive updates to this plugin beyond ones I've needed for a specific use case, but am unopposed to accepting a PR for this if it doesn't break existing functionality.

You can change the color of the title text of the notification by using "color," but the background might be trickier, since it seems to require applying a style to the notification as well.

**Comment by Guy-Sela** [comment]
> 

Thanks.

Works on android though, but not on ios, so I'm using the master version for ios, and this setup for android.

Is that intentional? Known? A bug? Or am I missing something?

**Comment by Guy-Sela** [comment]
> 

> I had some troubles building @timkellypa fork (I had this one using AndroidX and others with incompatible libraries). But I fixed by using [this plugin](https://github.com/dpa99c/cordova-plugin-androidx-adapter) created by @dpa99c
> 
> Next, you need to enable the AndroidX support by adding the next code into your project's config.xml file:
> 
> `<preference name="AndroidXEnabled" value="true" />`
> 
> Good luck and hope this helps!

@alixti @timkellypa 

Thanks.

Works on android though, but not on ios, so I'm using the master version for ios, and this setup for android.

Is that intentional? Known? A bug? Or am I missing something?

**Comment by gazben** [comment]
Any news on this PR?

**Pull request merged**
