### PR TITLE
iOS 10 local notifications fixed

### PR DESCRIPTION
**Pull request by spk0611**
Added local notification click event fix to pull request created by @uareurapid

### CODE REVIEW

**Comment by Tawpie** [comment]
:embarrassed face: how would I get this commit to test it? The master at https://github.com/spk0611/cordova-plugin-local-notifications errors during build iOS

**Comment by dotterbrasil** [comment]
It is not building for iOS on Phonegap Build.

**Comment by Tawpie** [comment]
@dotterbrasil if you could post the error message(s) I might be able to assist… I had many adventures getting it to build but managed to succeed.

**Comment by dotterbrasil** [comment]
Hi Tawpie! It builds for Android and Windows but fails for iOS with this message:
"Error - The following 3rd-party plugin is causing the build to fail and may need to be updated to a newer version: de.appplant.cordova.plugin.local-notification "

**Comment by Tawpie** [comment]
@dotterbrasil I hate to do this to you, but for me I had to use this sequence to load the plugin (I don’t use phone gap build so don’t know the commands for it)
cordova plugin rm de.appplant.cordova.plugin.local-notification
cordova plugin add https://github.com/spk0611/cordova-plugin-local-notifications#9ad32cf2059cdf9a54b4930b1c58ba76ef7e3a87
and I also needed to go into Xcode and ensure that XCode -> Preferences -> Locations and check if Command Line Tools is set to Xcode 8.
while you’re in Xcode, go to the build settings for your target and be certain “Enable Modules (C and Objective-C)” is turned on

and finally I had to edit plugin.xml (it’s in the plugins folder) to uncomment the line that commented out the cordova-plugman engine in order for the app to actually have access to the plugin.

FWIW, I built with the retail release of Xcode 8, cordova 6.3.1, iOS 3.9.2. The iOS cordova platform is old but needed because some of the plugins I use are too old for the newer cordova iOS platform releases.

Hope that helps...

**Comment by uareurapid** [comment]
anything else from the logs? it could help to solve your build issue...

**Comment by bobhuang1** [comment]
@spk0611 Great work! I used your branch and it worked great. I modified a few lines and got custom sound working. Here it is, AppLocalNotification.m:
    NSString userSound = notification.soundName;
    if ([self stringIsNullOrEmpty:notification.soundName])
    {

    }
    else if ([userSound isEqualToString:DEFAULT_SOUND])
    {
        content.sound = [UNNotificationSound defaultSound];
    }
    else if ([userSound hasPrefix:@"file:/"])
    {
        content.sound = [UNNotificationSound soundNamed:[self soundNameForAsset:userSound]];
    }
    else if ([userSound hasPrefix:@"res:"])
    {
        content.sound = [UNNotificationSound soundNamed:[self soundNameForResource:userSound]]
    }
//        content.sound = [UNNotificationSound defaultSound];

**Comment by bobhuang1** [comment]
Well, I answered my own question, please see this pull request:
https://github.com/spk0611/cordova-plugin-local-notifications/pull/1

**Comment by dotterbrasil** [comment]
@uareurapid  @Tawpie , thanks for the help. I was using 2 plugins:
< cordova-common-registerusernotificationsettings-mm > (NPM)
< cordova-plugin-local-notifications-mm >(NPM)

Then, i replace local-notifications with:
< https://github.com/notclive/cordova-plugin-local-notifications > (GIT)

iOS build show the "arm64" error.

I solve it removing < cordova-common-registerusernotificationsettings-mm > (NPM)

< https://github.com/notclive/cordova-plugin-local-notifications > (GIT) is working very well!!!!

Thank you guys!

**Comment by jamesdixon** [comment]
Any idea when this fix will be in?

**Comment by isuda** [comment]
Katzer commented in this thread about it: https://github.com/katzer/cordova-plugin-local-notifications/issues/1034#issuecomment-246987953

This hotfix might work in some situations, but it will fall down in a lot of other ways.

**Comment by bobhuang1** [comment]
Well, I am only using this hot fix for simple "now" type notifications and it worked great for me, so kudos @spk0611

**Comment by JuJu57** [comment]
Hey, just so you know, it worked well for me. Thanks @spk0611

**Comment by mishawagon** [comment]
@Tawpie's instructions helped me use this winning code, thank you @spk0611

**Comment by lucbonnin** [comment]
hi folks. I've tried to pull ios10 branch, compile using xcode8, checking "enable module C and objective C), enable background mode as usual but it is still not working on ios 10 :(  
driving me crazy

**Comment by mishawagon** [comment]
Try passing in a key value pair for 'at', as in at: date
Also, you can check if the scheduling happens and if the notification triggers by registering event handlers:
`        cordova.plugins.notification.local.on("schedule", function(notification) {
            console.log("scheduled: " + notification.id+" at "+notification.at+" text "+notification.text);
        });
        cordova.plugins.notification.local.on("trigger", function(notification) {
            console.log("Triggered: " + notification.id);
        });`

**Comment by lucbonnin** [comment]
@mishawagon I've tried adding your logs + a "at" key value/pair.
Log is well written both for scheduled and triggered but no trace of any notification on the ios device :(
I'm reading logs from safari dev mode with my iphone 6 connected over USB.

**Comment by mishawagon** [comment]
@lucbonnin Are you installing it with @Tawpie's method listed above or the normal way (since @katzer merged the fix)? Also, I noticed the local notifications don't fire if app is already foregrounded. This works for me because I only need to fire them when the app is in background. I don't have iOS 10 but my Test Flight tester with iOS 10 got it working after I did @Tawpie's fix a few days ago. It also worked in the simulator. I hope this helps a little bit, sorry I can't offer anything more at this point.

**Comment by ajaysaini95700** [comment]
Notifictaion is triggered successfully on ios 10 but notification is not showing on notification bar

**Comment by lucbonnin** [comment]
@mishawagon i've tried the katzer branch ios10 that include the @Tawpie fix.
I've tested it only on real device (ios10 iphone6) with safari debug data that indicate logs (so schedule is initialized and triggered).
I've just test it on background (as i was testing on foreground) but not working :(
On XCode i've checked location update+background fetch options (but not audio option as it was rejected by Apple because i don't use audio background mode)

**Comment by uareurapid** [comment]
@lucbonnin make sure you have allowed notifications for the app (does it prompt for authorization?)
you don´t need any special background modes for local notifications

**Comment by ajaysaini95700** [comment]
if app is in background then notification is showing on notification bar. if app is in foreground Notifictaion is triggered successfully but  it does not show on notification bar. i tested it on iphone 5s (ios 10).

**Comment by lucbonnin** [comment]
@uareurapid Yes notif allowed, prompted for authorization.
And delete then create app (not only update from xcode, some times buggy)

**Comment by uareurapid** [comment]
@lucbonnin @ajaysaini95700, if you´re trying with the app on foreground, make sure  you have the implemented the delegate method on your objective c/swift code
[](https://developer.apple.com/reference/usernotifications/unusernotificationcenterdelegate/1649518-usernotificationcenter?language=objc)

**Comment by lucbonnin** [comment]
@uareurapid Your link is related with ios native dev but we are using this plugin in a cordova environment (for me in IONIC 1), so am i missing something ?

**Comment by uareurapid** [comment]
@lucbonnin i´m using it with cordova too
afaik you don´t get a visual notification/alert on iOS 10, if the app is in foreground, but the delegate method will get called (and from there you can do what you want, including calling javascript code). Before iOS 10, when in foreground, the notification is not even delivered to the app, but to the OS itself (no delegate method called). It seems to me that you´re expecting the regular notification alert/message when the app is in foreground, but that´s not going to happen

**Comment by lucbonnin** [comment]
@uareurapid even in bgmode it is not showing notif data. But in bg mode i can't retrieve logs from safari so i'm a bit blind

**Comment by ajaysaini95700** [comment]
@uareurapid  this plugin work only when app is in background for ios10. and notification will show on notification bar when app will be in background ?

**Comment by lucbonnin** [comment]
Hi all @uareurapid @ajaysaini95700 @katzer 
I think i found the issue for my use case.
1st of all it is not working anymore on foreground mode (it was on ios9 or older) but it doesn't really matter as it is not really relevant to make it work on foreground.
In background i make it worked ONLY if on xcode i check the "audio,airplay and picture in picture" background mode.
I was using only "location updates", "background fetch" and "remote notifications" befeore ios10 and is was perfect. Now i suspect the plugin to work ONLY if this audio mode is activated (even if i don't use it).
Anyone can confirm this ?

My test case: 
- build app with this mode checked => it is working
- build app with this mode unchecked => no notification displayed :(

Am i right ?

**Comment by ajaysaini95700** [comment]
@ lucbonnin  i did not check the "audio,airplay and picture in picture" background mode.  but still i am getting notification when app is in background. 
can you check this file in your plugin ?
https://github.com/spk0611/cordova-plugin-local-notifications/blob/9ad32cf2059cdf9a54b4930b1c58ba76ef7e3a87/src/ios/APPLocalNotification.m

**Comment by lucbonnin** [comment]
@ajaysaini95700 I've beyondCompared it and i've the same version.
i'm using the katzer ios10 branch

**Comment by ajaysaini95700** [comment]
@uareurapid @katzer 
i want to show notification on notification bar when app is in foreground (it was on ios9 or older).
for this feature @uareurapid shared link [(https://developer.apple.com/reference/usernotifications/unusernotificationcenterdelegate/1649518-usernotificationcenter?language=objc)] this link is related with ios native 
but i am using plugin. so are you planning to implement this feature in plugin for ios 10 ?

**Comment by shi11** [comment]
even after adding the ios10 branch, it still wasn't working. 
making this change finally fixed it for me:
https://github.com/katzer/cordova-plugin-local-notifications/pull/1107/commits/5dad35f90e4d9bafc5465f085b2be85398638410

**Comment by ltfschoen** [comment]
Thank you @Tawpie for sharing your solution, I was able to deploy to an iPhone device with iOS 10 with Local Push Notifications working again. The plugin broke after I upgraded from Xcode 7 to Xcode 8.1.

**Comment by shadmehr** [comment]
I add plugin from below commit and it works :
cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications#fdf8470de329421370ef81c9efa12caab995c309

**Comment by zefrench** [comment]
I tried to replace the plugin with other repository branches and it still not works on ios10.
Was perfect on ios9. 
Someone is able to fix this ?

**Comment by dotterbrasil** [comment]
Hi Alex!

 

I´m using: https://github.com/notclive/cordova-plugin-local-notifications

 

It works perctly!!!

 

Eduardo

 

De: Alex [mailto:notifications@github.com] 
Enviada em: terça-feira, 20 de dezembro de 2016 19:06
Para: katzer/cordova-plugin-local-notifications <cordova-plugin-local-notifications@noreply.github.com>
Cc: dotterbrasil <eduardo@dotter.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [katzer/cordova-plugin-local-notifications] iOS 10 local notifications fixed (#1093)

 

I tried to replace the plugin with other repository branches and it still not works on ios10.
Was perfect on ios9.
Someone is able to fix this ?

**Comment by zefrench** [comment]
Hi @dotterbrasil,
Thanks for your help but it still does not works on ios10. On ios9 simulator it works. I don't understand..

**Comment by dotterbrasil** [comment]
Hi Alex.

 

It is working fine on iOS 10 for us… Maybe some plugins mismatching?

 

De: Alex [mailto:notifications@github.com] 
Enviada em: quinta-feira, 22 de dezembro de 2016 12:11
Para: katzer/cordova-plugin-local-notifications <cordova-plugin-local-notifications@noreply.github.com>
Cc: dotterbrasil <eduardo@dotter.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [katzer/cordova-plugin-local-notifications] iOS 10 local notifications fixed (#1093)

 

Hi @dotterbrasil <https://github.com/dotterbrasil> ,
Thanks for your help but it still does not works on ios10. On ios9 simulator it works. I don't understand..

**Comment by manojmohanan23** [comment]
I am also using the same plugin for local notification. It was working fine with iOS9 devices, as I updated my device to iOS10 notifications not working. I have tried all the solutions suggested in this thread. It will be helpful if someone could share any latest update on this.

Thanks
Manoj M

**Comment by jralfarog** [comment]
Hi @dotterbrasil Im using https://github.com/notclive/cordova-plugin-local-notifications and works fine on iOS10 but I can not change the icon and sound is not working (device only vibrate). Any help?

**Comment by rameshsharmaaspire** [comment]
To me the plugin is working in ios10 but the update function is not working thus not able to update Notification's icon or text upon completion of some xyz task. Does any one else has issue as I am having ? please confirm and guide.
For detail check this link: [](https://github.com/katzer/cordova-plugin-local-notifications/issues/1271)
Thanks.

**Comment by rwillett** [comment]
@rameshsharmaaspire create a new issue with #1188 so its clear what you are trying to do.

**Comment by rameshsharmaaspire** [comment]
@rwillett  I have already created issue there https://github.com/katzer/cordova-plugin-local-notifications/issues/1271 .let me know if I need to refine it or add more details to it.

Thanks 
Ramesh

**Comment by rwillett** [comment]
OK, I can see it now. 

I'm not the plugin developer, and just help on the issues.

**Comment by rameshsharmaaspire** [comment]
Okay fine. I am desperately waiting for response on that issue.

Thanks.

On Apr 17, 2017 12:48 PM, "Rob Willett" <notifications@github.com> wrote:

OK, I can see it now.

I'm not the plugin developer, and just help on the issues.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/katzer/cordova-plugin-local-notifications/pull/1093#issuecomment-294422785>,
or mute the thread

**Comment by auryn31** [comment]
Hey guys, are there any new information?
i tried today with:
`if (this.localNotifications.hasPermission()) {
      this.localNotifications.schedule({
        id: 4,
        title: 'YEHA!',
        text: 'Successfully sent a notification!',
        at: testdate,
        every: "second",
        sound: null
      });
      this.notificationTest = "tried to trigger notification!";
    }`
i have permissions, but i did not get any notification
not at builded ios app and not in the ion viewer
did anyone has an idea what i do wrong? :-D
thanks for help

**Pull request merged**
