### PR TITLE
Allow multiline notification message

### PR DESCRIPTION
**Pull request by fikri-marhan**
Currently notification message is trucated. This commit will allow the notification message to be multiline

### CODE REVIEW

**Comment by mix3d** [comment]
Is there value in having this configurable? I don't have a ton of experience with the BigTextStyle, but if it isn't truncated, will the user still be able to expand it?

**Comment by mix3d** [comment]
Would something like this be better?
```
if(options.getExpandedText != null) {
    builder.setStyle(new NotificationCompat.BigTextStyle().bigText(options.getExpandedText()));
}
```
This way we could specify different small/big text if needed?

**Comment by fikri-marhan** [comment]
I was testing it with Samsung Note 5, one drawback that I see with this is that if the notification is the first one, then its display just fine. But still gets truncated if its not the first one. 

A bit more research and I saw there is similar pull request #92  on the older version, not sure why its not supported in the new one.

I think #92 has better approach in configurability and we should just replicate it back. Just need to know why the support is dropped in the first place.

**Comment by sinedied** [comment]
It was already present on the older version, please merge this one 👍

**Comment by vishnurs** [comment]
Working perfectly in android. What is the fix for IOS?

**Comment by ilvalle** [comment]
Is there any update regarding this feature?

**Comment by katzer** [comment]
Has been added - Thanks.

**Pull request closed without merging**
